package poabus.ui;

import java.awt.BorderLayout;
import java.awt.Color;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JFrame;
import org.jxmapviewer.viewer.GeoPosition;
import poabus.domain.ILinhasService;
import poabus.domain.IParadasService;
import poabus.domain.Linha;
import poabus.domain.Parada;
import poabus.services.LinhasService;
import poabus.services.ParadasService;

public class JanelaConsulta extends javax.swing.JFrame {

    /**
     * Creates new form JanelaConsulta
     */
    public JanelaConsulta() {
        _paradasService = new ParadasService();
        _linhasService = new LinhasService();
        initComponents();
        initMyComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelMenu = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnBuscarLinha = new javax.swing.JButton();
        comboLinhas = new javax.swing.JComboBox();
        painelMapa = new javax.swing.JPanel();
        btnTodasAsParadas = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        painelMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Selecione a Linha:");
        painelMenu.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        btnBuscarLinha.setText("Buscar");
        btnBuscarLinha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarLinhaActionPerformed(evt);
            }
        });
        painelMenu.add(btnBuscarLinha, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 62, 213, -1));

        comboLinhas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboLinhasActionPerformed(evt);
            }
        });
        painelMenu.add(comboLinhas, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 31, 213, -1));

        painelMapa.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnTodasAsParadas.setText("Todas as Paradas");
        btnTodasAsParadas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTodasAsParadasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(painelMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTodasAsParadas, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(painelMapa, javax.swing.GroupLayout.DEFAULT_SIZE, 695, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(painelMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 484, Short.MAX_VALUE)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnTodasAsParadas))
                    .addComponent(painelMapa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTodasAsParadasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTodasAsParadasActionPerformed
        List<MyWaypoint> lstPoints = new ArrayList<MyWaypoint>();
        List<Parada> todasAsParadas = _paradasService.getAllParadas();

        for (Parada p : todasAsParadas) {
            double valor = 250; // ex: valor da consulta (criminalidade ou dist�ncia)
            GeoPosition loc = new GeoPosition(p.getLatitude(), p.getLongitude()); // ex: localiza��o da parada
            lstPoints.add(new MyWaypoint(Color.BLUE, valor, loc));
        }

        GeoPosition ptCentro = gerenciador.getSelecaoCentro();
        gerenciador.setPontos(lstPoints);

        this.repaint();
    }//GEN-LAST:event_btnTodasAsParadasActionPerformed

    private void btnBuscarLinhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarLinhaActionPerformed
        Linha l = (Linha) comboLinhas.getSelectedItem();
        List<MyWaypoint> lstPoints = new ArrayList<MyWaypoint>();
        List<Parada> paradas = l.getParadas();
        
        for (Parada p : paradas) {
            double valor = 250; // ex: valor da consulta (criminalidade ou dist�ncia)
            GeoPosition loc = new GeoPosition(p.getLatitude(), p.getLongitude()); // ex: localiza��o da parada
            lstPoints.add(new MyWaypoint(Color.BLUE, valor, loc));
        }
        GeoPosition ptCentro = gerenciador.getSelecaoCentro();
        gerenciador.setPontos(lstPoints);

        this.repaint();
    }//GEN-LAST:event_btnBuscarLinhaActionPerformed

    private void comboLinhasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboLinhasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboLinhasActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarLinha;
    private javax.swing.JButton btnTodasAsParadas;
    private javax.swing.JComboBox comboLinhas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPanel painelMapa;
    private javax.swing.JPanel painelMenu;
    // End of variables declaration//GEN-END:variables
    private GerenciadorMapa gerenciador;
    private final IParadasService _paradasService;
    private final ILinhasService _linhasService;

    private void initMyComponents() {
        GeoPosition poa = new GeoPosition(-30.05, -51.18);
        gerenciador = new GerenciadorMapa(poa, GerenciadorMapa.FonteImagens.VirtualEarth);

        painelMapa.setLayout(new BorderLayout());
        painelMapa.add(gerenciador.getMapKit(), BorderLayout.CENTER);

        populaComboLinhas();

        this.setSize(800, 600);
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.pack();
    }

    private void populaComboLinhas() {
        List<Linha> todasLinhas = _linhasService.getAllLinhas();
                        
        for (Linha l : todasLinhas) {
            comboLinhas.addItem(l);            
        }
    }
}
