package poabus.ui;

import java.awt.BorderLayout;
import java.awt.Color;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import org.jxmapviewer.viewer.GeoPosition;
import poabus.domain.ILinhasService;
import poabus.domain.IParadasService;
import poabus.domain.Linha;
import poabus.domain.Parada;
import poabus.services.LinhasService;
import poabus.services.ParadasService;

public class JanelaConsulta extends javax.swing.JFrame {

    /**
     * Creates new form JanelaConsulta
     */
    public JanelaConsulta() {
        super("PoaBus");
        _paradasService = new ParadasService();
        _linhasService = new LinhasService();
        initComponents();
        initMyComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelMenu = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnBuscarLinha = new javax.swing.JButton();
        comboLinhas = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstLinhas = new javax.swing.JList();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        btnLimpar = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        btnTodasAsParadas = new javax.swing.JButton();
        btnAddParada = new javax.swing.JButton();
        btnAtualizaLinhas = new javax.swing.JButton();
        btnAddByRaio = new javax.swing.JButton();
        btnTodasLinhasSelecionadas = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        btnAtualizarLinha = new javax.swing.JButton();
        btnLotacoes = new javax.swing.JButton();
        btnDetalhes = new javax.swing.JButton();
        btnHisto = new javax.swing.JButton();
        painelMapa = new javax.swing.JPanel();
        btnAutores = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        painelMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Selecione a Linha:");
        painelMenu.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, -1, -1));

        btnBuscarLinha.setText("Buscar");
        btnBuscarLinha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarLinhaActionPerformed(evt);
            }
        });
        painelMenu.add(btnBuscarLinha, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, 140, -1));

        comboLinhas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboLinhasActionPerformed(evt);
            }
        });
        painelMenu.add(comboLinhas, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 330, -1));

        jScrollPane1.setViewportView(lstLinhas);

        painelMenu.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 270, 150));
        painelMenu.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 260, 10));

        jLabel2.setText("Linhas das paradas selecionadas");
        painelMenu.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, -1, -1));

        btnLimpar.setText("Limpar");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });
        painelMenu.add(btnLimpar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 460, 260, -1));
        painelMenu.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 440, 260, 10));

        btnTodasAsParadas.setText("Todas as Paradas");
        btnTodasAsParadas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTodasAsParadasActionPerformed(evt);
            }
        });
        painelMenu.add(btnTodasAsParadas, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 490, 260, -1));

        btnAddParada.setText("Adicionar Parada");
        btnAddParada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddParadaActionPerformed(evt);
            }
        });
        painelMenu.add(btnAddParada, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 140, -1));

        btnAtualizaLinhas.setText("Filtrar Linhas");
        btnAtualizaLinhas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizaLinhasActionPerformed(evt);
            }
        });
        painelMenu.add(btnAtualizaLinhas, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 320, 130, -1));

        btnAddByRaio.setText("Adicionar Por Raio");
        btnAddByRaio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddByRaioActionPerformed(evt);
            }
        });
        painelMenu.add(btnAddByRaio, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 140, -1));

        btnTodasLinhasSelecionadas.setText("Todas Linhas");
        btnTodasLinhasSelecionadas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTodasLinhasSelecionadasActionPerformed(evt);
            }
        });
        painelMenu.add(btnTodasLinhasSelecionadas, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 360, 130, -1));

        jButton1.setText("Adicionar Linha");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        painelMenu.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, 140, -1));

        btnAtualizarLinha.setText("Atualizar");
        btnAtualizarLinha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizarLinhaActionPerformed(evt);
            }
        });
        painelMenu.add(btnAtualizarLinha, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 140, -1));

        btnLotacoes.setText("Lotações");
        btnLotacoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLotacoesActionPerformed(evt);
            }
        });
        painelMenu.add(btnLotacoes, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 140, -1));

        btnDetalhes.setText("Ver Detalhes");
        btnDetalhes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDetalhesActionPerformed(evt);
            }
        });
        painelMenu.add(btnDetalhes, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, 140, -1));

        btnHisto.setText("Ver Histograma");
        btnHisto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHistoActionPerformed(evt);
            }
        });
        painelMenu.add(btnHisto, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 400, 130, -1));

        painelMapa.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAutores.setText("+");
        btnAutores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAutoresActionPerformed(evt);
            }
        });
        painelMapa.add(btnAutores, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 10, 50, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addComponent(painelMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(painelMapa, javax.swing.GroupLayout.PREFERRED_SIZE, 611, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(painelMenu, javax.swing.GroupLayout.DEFAULT_SIZE, 536, Short.MAX_VALUE)
                    .addComponent(painelMapa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTodasAsParadasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTodasAsParadasActionPerformed
        List<MyWaypoint> lstPoints = new ArrayList<MyWaypoint>();
        List<Parada> todasAsParadas = _paradasService.getAllParadas();

        for (Parada p : todasAsParadas) {
            double valor = 250; // ex: valor da consulta (criminalidade ou dist�ncia)
            GeoPosition loc = new GeoPosition(p.getLatitude(), p.getLongitude()); // ex: localiza��o da parada
            lstPoints.add(new MyWaypoint(Color.BLUE, valor, loc));
        }
        
        gerenciador.setPontos(lstPoints);

        this.repaint();
    }//GEN-LAST:event_btnTodasAsParadasActionPerformed

    private void btnBuscarLinhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarLinhaActionPerformed
        Linha l = (Linha) comboLinhas.getSelectedItem();
        List<MyWaypoint> lstPoints = new ArrayList<MyWaypoint>();
        List<Parada> paradas = l.getParadas();
        
        for (Parada p : paradas) {            
            double valor = 250; // ex: valor da consulta (criminalidade ou dist�ncia)
            GeoPosition loc = new GeoPosition(p.getLatitude(), p.getLongitude()); // ex: localiza��o da parada
            lstPoints.add(new MyWaypoint(Color.green, valor, loc));           
        }
        GeoPosition ptCentro = gerenciador.getSelecaoCentro();
        gerenciador.setPontos(lstPoints);

        this.repaint();
    }//GEN-LAST:event_btnBuscarLinhaActionPerformed

    private void comboLinhasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboLinhasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboLinhasActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        // TODO add your handling code here:
        List<MyWaypoint> lstPoints = new ArrayList<MyWaypoint>();
        if(!lstModel.isEmpty()){
        lstModel.clear();
        }
        paradasSelecionadas.clear();
        paradasSel.clear();
        gerenciador.setPontos(lstPoints);
        this.repaint();
    }//GEN-LAST:event_btnLimparActionPerformed

    private void btnAddParadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddParadaActionPerformed
        // TODO add your handling code here:
        GeoPosition g = gerenciador.getSelecaoCentro();
        Parada p = _paradasService.getParadaNearLocation(g.getLongitude(), g.getLatitude());
        GeoPosition gf = new GeoPosition(p.getLatitude(), p.getLongitude());
        MyWaypoint ponto = new MyWaypoint(Color.RED, 250, gf);
        paradasSel.add(ponto);
        paradasSelecionadas.add(p);
        gerenciador.setPontos(paradasSel);
        this.repaint();
    }//GEN-LAST:event_btnAddParadaActionPerformed
    
    private DefaultListModel lstModel;
    
    private void btnAtualizaLinhasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizaLinhasActionPerformed
                   
        List<Linha> linhasDasParadas = _linhasService.getLinhasPassamParadas(paradasSelecionadas);
             
        lstModel = new DefaultListModel(); 
        
        if(linhasDasParadas.size() > 0){
            for(Linha l : linhasDasParadas){            
                lstModel.add(lstModel.size(), l);
            }                           
        }
        lstLinhas.setModel(lstModel);                        
    }//GEN-LAST:event_btnAtualizaLinhasActionPerformed

    private void btnAddByRaioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddByRaioActionPerformed
        // TODO add your handling code here:
        List<MyWaypoint> lstPoints = new ArrayList<MyWaypoint>();
        double raio = gerenciador.getRaioD();        
        GeoPosition centro = gerenciador.getSelecaoCentro();        
        List<Parada> paradas = _paradasService.getParadasByRaio(raio, centro.getLatitude(), centro.getLongitude());
        paradasSelecionadas.addAll(paradas);
        for(Parada p : paradasSelecionadas){
            double valor = 250; // ex: valor da consulta (criminalidade ou dist�ncia)
            GeoPosition loc = new GeoPosition(p.getLatitude(), p.getLongitude()); // ex: localiza��o da parada
            lstPoints.add(new MyWaypoint(Color.RED, valor, loc));
        }
        GeoPosition ptCentro = gerenciador.getSelecaoCentro();
        
        gerenciador.setPontos(lstPoints);
        this.repaint();
    }//GEN-LAST:event_btnAddByRaioActionPerformed

    private void btnTodasLinhasSelecionadasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTodasLinhasSelecionadasActionPerformed
        // TODO add your handling code here:
        List<Linha> todasLinhas = _linhasService.getTodasLinhasPassamParadas(paradasSelecionadas);
        lstModel = new DefaultListModel(); 
        
        if(todasLinhas.size() > 0){
            for(Linha l : todasLinhas){            
                lstModel.add(lstModel.size(), l);
            }                           
        }
        lstLinhas.setModel(lstModel);  
    }//GEN-LAST:event_btnTodasLinhasSelecionadasActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        CadastradorDeLinha cadastro = new CadastradorDeLinha(_linhasService);
        cadastro.setVisible(rootPaneCheckingEnabled);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnAtualizarLinhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarLinhaActionPerformed
        // TODO add your handling code here:
        comboLinhas.removeAllItems();
        populaComboLinhas();
        comboLinhas.repaint();
    }//GEN-LAST:event_btnAtualizarLinhaActionPerformed

    private void btnLotacoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLotacoesActionPerformed
        // TODO add your handling code here:
        ExibeLotacoes lotacoes = new ExibeLotacoes(_linhasService);        
        lotacoes.setVisible(rootPaneCheckingEnabled);
    }//GEN-LAST:event_btnLotacoesActionPerformed

    private void btnDetalhesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetalhesActionPerformed
        // TODO add your handling code here:
        if(paradasSelecionadas.size() > 1){
            JOptionPane.showMessageDialog(null, "Mais de uma parada selecionada!");
            return;
        }
        Parada p = paradasSelecionadas.get(0);
        ExibeDetalhes detalhes = new ExibeDetalhes(p);
        detalhes.setVisible(rootPaneCheckingEnabled);
    }//GEN-LAST:event_btnDetalhesActionPerformed

    private void btnHistoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHistoActionPerformed
        // TODO add your handling code here:
        Grafico grafico = new Grafico(_linhasService.getAllLinhas());
        grafico.setVisible(rootPaneCheckingEnabled);
    }//GEN-LAST:event_btnHistoActionPerformed

    private void btnAutoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAutoresActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Henrique Urruth, Kim dos Santos e Thomas Berquó");
    }//GEN-LAST:event_btnAutoresActionPerformed
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddByRaio;
    private javax.swing.JButton btnAddParada;
    private javax.swing.JButton btnAtualizaLinhas;
    private javax.swing.JButton btnAtualizarLinha;
    private javax.swing.JButton btnAutores;
    private javax.swing.JButton btnBuscarLinha;
    private javax.swing.JButton btnDetalhes;
    private javax.swing.JButton btnHisto;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnLotacoes;
    private javax.swing.JButton btnTodasAsParadas;
    private javax.swing.JButton btnTodasLinhasSelecionadas;
    private javax.swing.JComboBox comboLinhas;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JList lstLinhas;
    private javax.swing.JPanel painelMapa;
    private javax.swing.JPanel painelMenu;
    // End of variables declaration//GEN-END:variables
    private GerenciadorMapa gerenciador;
    private final IParadasService _paradasService;
    private final ILinhasService _linhasService;
    private List<Parada> paradasSelecionadas;
    private List<MyWaypoint> paradasSel;

    private void initMyComponents() {
        lstModel = new DefaultListModel();
        GeoPosition poa = new GeoPosition(-30.05, -51.18);
        gerenciador = new GerenciadorMapa(poa, GerenciadorMapa.FonteImagens.VirtualEarth);
        paradasSelecionadas = new ArrayList<Parada>();
        paradasSel = new ArrayList<MyWaypoint>();
        painelMapa.setLayout(new BorderLayout());
        painelMapa.add(gerenciador.getMapKit(), BorderLayout.CENTER);

        populaComboLinhas();

        this.setSize(800, 600);
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.pack();
    }       

    private void populaComboLinhas() {
                        
        List<Linha> todasLinhas = _linhasService.getAllLinhas();
        List<Linha> lotacoes = _linhasService.getAllLotacoes();
                                        
        for (Linha l : todasLinhas) {
            if(l.getTipo() == 'O'){
                comboLinhas.addItem(l);                        
            }
        }               
    }              
}
