package poabus.ui;

import java.awt.BorderLayout;
import java.awt.Color;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JFrame;
import org.jxmapviewer.viewer.GeoPosition;
import poabus.domain.ILinhasService;
import poabus.domain.IParadasService;
import poabus.domain.Linha;
import poabus.domain.Parada;
import poabus.services.LinhasService;
import poabus.services.ParadasService;

public class JanelaConsulta extends javax.swing.JFrame {

    /**
     * Creates new form JanelaConsulta
     */
    public JanelaConsulta() {
        _paradasService = new ParadasService();
        _linhasService = new LinhasService();
        initComponents();
        initMyComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelMenu = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnBuscarLinha = new javax.swing.JButton();
        comboLinhas = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstLinhas = new javax.swing.JList();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        btnLimpar = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        btnTodasAsParadas = new javax.swing.JButton();
        btnAddParada = new javax.swing.JButton();
        btnAtualizaLinhas = new javax.swing.JButton();
        painelMapa = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        painelMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Selecione a Linha:");
        painelMenu.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        btnBuscarLinha.setText("Buscar");
        btnBuscarLinha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarLinhaActionPerformed(evt);
            }
        });
        painelMenu.add(btnBuscarLinha, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 260, -1));

        comboLinhas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboLinhasActionPerformed(evt);
            }
        });
        painelMenu.add(comboLinhas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 260, -1));

        jScrollPane1.setViewportView(lstLinhas);

        painelMenu.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 260, 73));
        painelMenu.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 260, 10));

        jLabel2.setText("Linhas das paradas selecionadas");
        painelMenu.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, -1, -1));

        btnLimpar.setText("Limpar");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });
        painelMenu.add(btnLimpar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, 260, -1));
        painelMenu.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 260, 10));

        btnTodasAsParadas.setText("Todas as Paradas");
        btnTodasAsParadas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTodasAsParadasActionPerformed(evt);
            }
        });
        painelMenu.add(btnTodasAsParadas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 400, 260, -1));

        btnAddParada.setText("Adicionar Parada");
        btnAddParada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddParadaActionPerformed(evt);
            }
        });
        painelMenu.add(btnAddParada, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 140, -1));

        btnAtualizaLinhas.setText("Atualizar Linhas");
        btnAtualizaLinhas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizaLinhasActionPerformed(evt);
            }
        });
        painelMenu.add(btnAtualizaLinhas, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 240, 130, -1));

        painelMapa.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(painelMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(painelMapa, javax.swing.GroupLayout.PREFERRED_SIZE, 532, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(painelMenu, javax.swing.GroupLayout.DEFAULT_SIZE, 427, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(painelMapa, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTodasAsParadasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTodasAsParadasActionPerformed
        List<MyWaypoint> lstPoints = new ArrayList<MyWaypoint>();
        List<Parada> todasAsParadas = _paradasService.getAllParadas();

        for (Parada p : todasAsParadas) {
            double valor = 250; // ex: valor da consulta (criminalidade ou dist�ncia)
            GeoPosition loc = new GeoPosition(p.getLatitude(), p.getLongitude()); // ex: localiza��o da parada
            lstPoints.add(new MyWaypoint(Color.BLUE, valor, loc));
        }
        
        gerenciador.setPontos(lstPoints);

        this.repaint();
    }//GEN-LAST:event_btnTodasAsParadasActionPerformed

    private void btnBuscarLinhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarLinhaActionPerformed
        Linha l = (Linha) comboLinhas.getSelectedItem();
        List<MyWaypoint> lstPoints = new ArrayList<MyWaypoint>();
        List<Parada> paradas = l.getParadas();
        
        for (Parada p : paradas) {
            double valor = 250; // ex: valor da consulta (criminalidade ou dist�ncia)
            GeoPosition loc = new GeoPosition(p.getLatitude(), p.getLongitude()); // ex: localiza��o da parada
            lstPoints.add(new MyWaypoint(Color.BLUE, valor, loc));
        }
        GeoPosition ptCentro = gerenciador.getSelecaoCentro();
        gerenciador.setPontos(lstPoints);

        this.repaint();
    }//GEN-LAST:event_btnBuscarLinhaActionPerformed

    private void comboLinhasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboLinhasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboLinhasActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        // TODO add your handling code here:
        List<MyWaypoint> lstPoints = new ArrayList<MyWaypoint>();
        paradasSel.clear();
        gerenciador.setPontos(lstPoints);
        this.repaint();
    }//GEN-LAST:event_btnLimparActionPerformed

    private void btnAddParadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddParadaActionPerformed
        // TODO add your handling code here:
        GeoPosition g = gerenciador.getSelecaoCentro();
        Parada p = _paradasService.getParadaNearLocation(g.getLongitude(), g.getLatitude());
        GeoPosition gf = new GeoPosition(p.getLatitude(), p.getLongitude());
        MyWaypoint ponto = new MyWaypoint(Color.RED, 250, gf);
        paradasSel.add(ponto);
        paradasSelecionadas.add(p);
        gerenciador.setPontos(paradasSel);
        this.repaint();
    }//GEN-LAST:event_btnAddParadaActionPerformed

    private void btnAtualizaLinhasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizaLinhasActionPerformed
        // TODO add your handling code here:                
        List<Linha> linhasDasParadas = _linhasService.getLinhasPassamParadas(paradasSelecionadas);
        for(Linha l : linhasDasParadas){
            System.out.println("Linha: " + l.getNome());
        }
    }//GEN-LAST:event_btnAtualizaLinhasActionPerformed
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddParada;
    private javax.swing.JButton btnAtualizaLinhas;
    private javax.swing.JButton btnBuscarLinha;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnTodasAsParadas;
    private javax.swing.JComboBox comboLinhas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JList lstLinhas;
    private javax.swing.JPanel painelMapa;
    private javax.swing.JPanel painelMenu;
    // End of variables declaration//GEN-END:variables
    private GerenciadorMapa gerenciador;
    private final IParadasService _paradasService;
    private final ILinhasService _linhasService;
    private List<Parada> paradasSelecionadas;
    private List<MyWaypoint> paradasSel;

    private void initMyComponents() {
        GeoPosition poa = new GeoPosition(-30.05, -51.18);
        gerenciador = new GerenciadorMapa(poa, GerenciadorMapa.FonteImagens.VirtualEarth);
        paradasSelecionadas = new ArrayList<Parada>();
        paradasSel = new ArrayList<MyWaypoint>();
        painelMapa.setLayout(new BorderLayout());
        painelMapa.add(gerenciador.getMapKit(), BorderLayout.CENTER);

        populaComboLinhas();

        this.setSize(800, 600);
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.pack();
    }       

    private void populaComboLinhas() {
        List<Linha> todasLinhas = _linhasService.getAllLinhas();
                        
        for (Linha l : todasLinhas) {
            comboLinhas.addItem(l);            
        }
    }        
}
